Build refactoring
genexuslabs/JavaClasses pull request #307
Opened 2020-11-10 13:11 UTC by jechague

- Add GitHub Actions build for PRs and branch status
- Add dispatch for internal builds
- Protect workflows in CODEOWNERS

Please, do not mark as _Ready for Review_ until runners are installed

2020-11-10 13:16 UTC, jechague commented on .github/updatePOMVersion.sh
> +fi
@anaiberta: this code is taken _as is_ from our internal build configuration but I'm not sure we should continue to use it. We no longer use the packages generated from PR builds so I think we could safely remove it. However, we could use this script to start using the master version + 100 in the beta branch. 

Could you also help me see whether I'm missing any special project configuration (eg. Mizuho, Corona, etc.) in this script?

2020-11-10 16:50 UTC, anaiberta requested changes
Some things to review (after a first overview).

2020-11-10 16:50 UTC, anaiberta commented on .github/workflows/Build.yml
> +      - 'beta'
'beta-corona' is missed.

2020-11-11 13:52 UTC, jechague commented on .github/workflows/Build.yml
> +          NexusURL=${{ secrets.NEXUS_MAVEN_SNAPSHOTS }}
This was leftover code from our internal build script. Fixed in 47e1852

2020-11-11 13:53 UTC, jechague commented on .github/workflows/Build.yml
> +        echo "::set-output name=IsPrerelease::$IsPrerelease"
Fixed in 47e1852

2020-11-11 13:54 UTC, jechague commented on .github/workflows/Build.yml
> +      - 'beta'
Fixed in 9468f48

2020-11-11 14:00 UTC, jechague commented
The necessary changes to our internal build infrastructure are in place so we can start applying these changes to the beta branch

2020-11-12 16:27 UTC, anaiberta approved these changes

2020-11-12 16:29 UTC, anaiberta commented on .github/updatePOMVersion.sh
> +    echo "## Updaing pom.xml version to: $newVersion"
```suggestion
    echo "## Updating pom.xml version to: $newVersion"
```

2020-11-12 16:31 UTC, jechague commented on .github/updatePOMVersion.sh
> +fi
This was fixed in c98a704

2020-11-12 16:34 UTC, anaiberta approved these changes

2020-11-12 18:42 UTC, merged