GeneXus compression module
genexuslabs/JavaClasses pull request #874
Opened 2024-06-04 20:24 UTC by tomas-sexenian

2025-03-18 19:06 UTC, tomas-sexenian commented
@iroqueta I need regular code review
@sgrampone I need security-related code review

Thanks!

2025-03-19 14:10 UTC, iroqueta commented on gxcompress/src/main/java/com/genexus/compression/GXCompressor.java
> +import org.apache.commons.compress.compressors.gzip.GzipParameters;
Unused import statement

2025-03-19 14:11 UTC, iroqueta commented on gxcompress/src/main/java/com/genexus/compression/GXCompressor.java
> +		while ((entry = tis.getNextTarEntry()) != null) {
'getNextTarEntry()' is deprecated

2025-03-19 14:12 UTC, iroqueta requested changes
Check comments

2025-03-19 18:47 UTC, iroqueta submitted a review, later dismissed

2025-04-08 19:19 UTC, sgrampone submitted a review, later dismissed
All the concerns that were raised have now been addressed and resolved

2025-07-02 19:13 UTC, merged